BACKGROUND_COLOR = "#B1DDC6"

IMAGE_BG_FRONT = "./images/card_front.png"
IMAGE_BG_BACK = "./images/card_back.png"
IMAGE_RIGHT = "./images/right.png"
IMAGE_WRONG = "./images/wrong.png"
WORDS_DATA_FILE = "./data/french_words.csv"
LEARNED_WORDS_DATA_FILE = "./data/learned_french_words.csv"

WINDOW_PADX = 50
WINDOW_PADY = 50

CANVAS_SIZE_WIDTH = 800 # Size of Logo image
CANVAS_SIZE_HEIGHT = 526 # Size of Logo image

IMAGE_BG_LOCATION_X = CANVAS_SIZE_WIDTH/2
IMAGE_BG_LOCATION_Y = CANVAS_SIZE_HEIGHT/2
LANGUAGE_Y = 150
WORD_Y = 263

FONT_NAME = "Arial"
FONT_LANGUAGE_SIZE = 40
FONT_WORD_SIZE = 60
FONT_LANGUAGE_STYLE = "italic"
FONT_WORD_STYLE = "bold"

BUTTON_TEXT_COLOR = "white"
BUTTON_FONT_NAME = FONT_NAME
BUTTON_FONT_SIZE = 14
BUTTON_FONT_STYLE = FONT_WORD_STYLE
BUTTON_FG_COLOR = "gray"
BUTTON_HOVER_COLOR = "black"

BUTTON_MESSAGEBOX_FG_COLOR = "white"

TIME_BEFORE_CORRECTION = 3000 # ms